#ifndef COMPONENTSCORE_VERSION_H
#define COMPONENTSCORE_VERSION_H

#define COMPONENTSCORE_VERSION_STR "1.4.0"
/*
   COMPONENTSCORE_VERSION is (major << 16) + (minor << 8) + patch.
*/
#define COMPONENTSCORE_VERSION 0x010400
/*
   can be used like #if (COMPONENTSCORE_VERSION >= COMPONENTSCORE_VERSION_CHECK(1, 1, 0))
*/
#define COMPONENTSCORE_VERSION_CHECK(major, minor, patch) ((major<<16)|(minor<<8)|(patch))

#endif // COMPONENTSCORE_VERSION_H
